language: python
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.7-dev
install:
  - pip3 install pylint
  - pip3 install -r requirements.txt
script:
  - pylint server.py
  - gunicorn server:APP -b 127.0.0.1:8080 > /dev/null &
